"use client";

import { useState } from "react";
import { articles, projects } from "@/lib/content";

export default function Home() {
  const [crt, setCrt] = useState(true);
  return <main className={`app-shell ${crt ? "" : "crt-off"}`}>
    <div className="crt-overlay" aria-hidden="true" />
    <SiteHeader crt={crt} onCrt={() => setCrt(!crt)} />
    <section className="hero page-grid" id="top"><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> SYSTEM ONLINE <span className="eyebrow-line" /> CHICAGO / IL</div><h1>BUILD<br /><em>BETTER</em><br />SYSTEMS<span className="cursor">_</span></h1><p className="hero-lede">Technology architecture, security thinking, and field-tested ideas for people building what’s next.</p><div className="hero-actions"><a className="button button-primary" href="/projects">Explore the work <span>↗</span></a><a className="text-link" href="/newsletter">Enter the signal <span>↗</span></a></div></div><div className="hero-console"><div className="console-top"><span>NEON_FORGE / BOOT_SEQUENCE</span><span>v.2.0.26</span></div><div className="boot-log"><p><span>&gt;</span> INITIALIZING KNOWLEDGE OS...</p><p><span>&gt;</span> MOUNTING /FIELD_NOTES <b>OK</b></p><p><span>&gt;</span> INDEXING 147 ARTIFACTS <b>OK</b></p><p><span>&gt;</span> USER FOUND: <strong>CHRIS_HIRSCHAUER</strong></p><p className="access"><span>&gt;</span> ACCESS GRANTED<span className="blink">▌</span></p></div><div className="console-divider" /><div className="console-stat"><span>CURRENT FOCUS</span><strong>HUMAN-SCALE AI</strong></div><div className="console-stat"><span>BUILD STATUS</span><strong className="green">● EXPLORING</strong></div><div className="console-footer">[ homepage / command center ]</div></div></section>
    <section className="signal-strip"><div><span className="strip-label">NEON//FORGE DIRECTORY</span><strong>Choose your route.</strong></div><div className="strip-meta">04 DESTINATIONS <span>→</span> LIVE</div></section>
    <section className="directory page-grid"><div className="section-label"><span>01</span><span>ACCESS<br />DIRECTORY</span></div><div className="directory-grid"><DirectoryCard number="01" title="PROJECTS" description="Systems, experiments, and architecture built in the open." href="/projects" /><DirectoryCard number="02" title="BOOKS" description="Field guides and notebooks for technically curious builders." href="/books" /><DirectoryCard number="03" title="THE SIGNAL" description="Newsletter, podcast, and weekly transmissions." href="/newsletter" /><DirectoryCard number="04" title="THE VAULT" description="Articles, tutorials, missions, and the knowledge archive." href="/vault" /></div></section>
    <section className="section page-grid home-latest"><div className="section-label"><span>02</span><span>LATEST<br />TRANSMISSION</span></div><div className="section-body"><div className="section-intro"><h2>Signal in<br /><em>the noise.</em></h2><a className="text-link" href="/vault">Open the vault <span>↗</span></a></div><div className="notes-list">{articles.slice(0,2).map((article) => <a className="note" href={`/vault/${article.slug}`} key={article.slug}><span className="note-date">{article.category} / {article.readTime}</span><strong>{article.title}</strong><span className="note-arrow">↗</span></a>)}</div></div></section>
    <section className="home-projects page-grid"><div className="section-label"><span>03</span><span>ACTIVE<br />SYSTEMS</span></div><div className="section-body"><div className="section-intro"><h2>Proof over<br /><em>promises.</em></h2><a className="text-link" href="/projects">View all projects <span>↗</span></a></div><div className="project-list">{projects.slice(0,2).map((project,index) => <a className="project-card" href={`/projects#${project.name.toLowerCase().replaceAll(" ","-")}`} key={project.name}><div className="project-number">0{index+1}</div><div><div className="card-kicker">{project.type}</div><h3>{project.name}<span>↗</span></h3><p>{project.description}</p></div><div className="card-index">[ OPEN ]</div></a>)}</div></div></section>
    <footer className="site-footer"><a className="brand" href="#top"><span className="brand-mark">N</span><span>STRATAGEM</span></a><span>© 2026 CHRIS HIRSCHAUER</span></footer>
  </main>;
}

function SiteHeader({crt,onCrt}:{crt:boolean;onCrt:()=>void}) { return <header className="site-header"><a className="brand" href="/"><span className="brand-mark">N</span><span>STRATAGEM</span></a><nav className="desktop-nav"><a href="/projects">01 / PROJECTS</a><a href="/newsletter">02 / SIGNAL</a><a href="/books">03 / BOOKS</a><a href="/vault">04 / VAULT</a></nav><div className="header-actions"><button className="mode-toggle" onClick={onCrt}>CRT <span>{crt ? "●" : "○"}</span></button></div></header>; }
function DirectoryCard({number,title,description,href}:{number:string;title:string;description:string;href:string}) { return <a className="directory-card" href={href}><span className="project-number">{number}</span><div><div className="card-kicker">ACCESS MODULE</div><h2>{title}<span>↗</span></h2><p>{description}</p></div></a>; }
